# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Salman Munaf
title: Software Engineer
email: salmanmunaf96@gmail.com
website: https://github.com/salmanmunaf

# Social links
# twitter_username: facespics
github_username:  salmanmunaf
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: salman96
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Salman and I am a recent graduate from LUMS with a major in Computer Science and a minor in Mathematics. I am interested in the design and implementation of systems guided by theoretical principles, at the intersection of networking, distributed systems and security. I enjoy researching and reading about problems in my area of interest; and creating unique algorithms to solve them.

  - Languages: Python, C++, NodeJS/Javascript, React, HTML, CSS, Haskell, GoLang, SQL, x86-64 Assembly
  - Libraries: Socket.IO, Numpy, Matplotlib, Pandas, Scikit-learn, Seaborn
  - Testbeds: PlanetLab, Emulab
  - Misc: LaTeX, Git

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Travelling
   - Community service
   - Sports (Swimming, Tennis, Cricket, and Football)

# Footer
# footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
